### ISSUE TITLE
Mismatch in number of iterations in the paper and the readme

### ISSUE THREAD

**Issue by egorsmkv** [charactr-platform/vocos#11]
The paper says there's 2M of iterations
The readme says there's 2.5M of iterations 

What is the truth?

**Comment by lexkoro** [comment]
https://github.com/charactr-platform/vocos#pre-trained-models

**Comment by hubertsiuzdak** [comment]
The experiments conducted in the paper included training baseline models and different variations of Vocos for up to 1M iterations. 

The variant of Vocos that performed the best was chosen and trained further up to 2.5M iterations using both EnCodec and mel-spec features. We have made these two checkpoints publicly available.

I hope this explanation is clearer now.

**Comment by egorsmkv** [comment]
Thank you, @hubertsiuzdak
