### ISSUE TITLE
training error.

### ISSUE THREAD

**Issue by xiaoyangnihao** [charactr-platform/vocos#12]
hi, I met this error:
I fill train and valid path in configs/vocos.yaml and use cli: "python train.py -c configs/vocos.yaml",  error happens: "train.py: error: Parser key "data": 'type' object is not subscriptable".

how should i slove it? many thanks.
@hubertsiuzdak

**Comment by egorsmkv** [comment]
Hello. I encountered the same error. Problem is the version of Python. 

What's your version?

**Comment by egorsmkv** [comment]
Python 3.10 you need

**Comment by xiaoyangnihao** [comment]
Thanks a lot, I will try this version.

**Comment by scutcsq** [comment]
> Python 3.10 you need

I used Python 3.10 but still encountered this error

**Comment by egorsmkv** [comment]
Check again which Python version you're using

**Comment by scutcsq** [comment]
> Check again which Python version you're using

My Python version is 3.10.12, and now  I encountered the problem "Parser key 'model' : Problem with given class_path 'vocos.experiment.VocosExp': Parser key "feature_extractor": listdir:path should be string, bytes, os.PathLike, integer or None, not Path". Would you know how to fix it?
