### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by QinHsiu** [charactr-platform/vocos#16]
Thanks for your opensource, when I try to run this model, I face the following problem: 
File "/mnt/nfs/dev-aigc-0/data1/xiuyuanqin/work/vocos/vocos/modules.py", line 109, in ResBlock1
    dilation: tuple[int] = (1, 3, 5),
TypeError: 'type' object is not subscriptable
could you help me with this problem?

**Comment by QinHsiu** [comment]
I have fixed this problem by up the python verision from 3.8 to 3.9

**Comment by GitYesm** [comment]
> I have fixed this problem by up the python verision from 3.8 to 3.9
I tried, but it still couldn't

**Comment by Jackiexiao** [comment]
upgrade to python 3.10 or use 
```
from typing import Tuple
Tuple[int]
```
