### ISSUE TITLE
"error: No module named 'encodec'" while training a vocos

### ISSUE THREAD

**Issue by P0rUnaCabeza** [charactr-platform/vocos#41]
I was trying to train a vocos and I ran the command  `train.py -c configs/vocos.yaml`, while it showed this error: 
`(autodl_test) root@autodl-container-da7148a975-fb23289d:~/autodl-tmp/PycharmProjects/vocos-main# python train.py -c configs/vocos.yaml
usage: train.py [-h] [-c CONFIG] [--print_config[=flags]] [--seed_everything SEED_EVERYTHING] [--trainer CONFIG] [--trainer.logger.help CLASS_PATH_OR_NAME]
                [--trainer.logger LOGGER] [--trainer.enable_checkpointing {true,false}] [--trainer.callbacks.help CLASS_PATH_OR_NAME] [--trainer.callbacks CALLBACKS]
                [--trainer.default_root_dir DEFAULT_ROOT_DIR] [--trainer.gradient_clip_val GRADIENT_CLIP_VAL] [--trainer.gradient_clip_algorithm GRADIENT_CLIP_ALGORITHM]
                [--trainer.num_nodes NUM_NODES] [--trainer.num_processes NUM_PROCESSES] [--trainer.devices DEVICES] [--trainer.gpus GPUS]
                [--trainer.auto_select_gpus {true,false}] [--trainer.tpu_cores TPU_CORES] [--trainer.ipus IPUS] [--trainer.enable_progress_bar {true,false}]
                [--trainer.overfit_batches OVERFIT_BATCHES] [--trainer.track_grad_norm TRACK_GRAD_NORM] [--trainer.check_val_every_n_epoch CHECK_VAL_EVERY_N_EPOCH]
                [--trainer.fast_dev_run FAST_DEV_RUN] [--trainer.accumulate_grad_batches ACCUMULATE_GRAD_BATCHES] [--trainer.max_epochs MAX_EPOCHS]
                [--trainer.min_epochs MIN_EPOCHS] [--trainer.max_steps MAX_STEPS] [--trainer.min_steps MIN_STEPS] [--trainer.max_time MAX_TIME]
                [--trainer.limit_train_batches LIMIT_TRAIN_BATCHES] [--trainer.limit_val_batches LIMIT_VAL_BATCHES] [--trainer.limit_test_batches LIMIT_TEST_BATCHES]
                [--trainer.limit_predict_batches LIMIT_PREDICT_BATCHES] [--trainer.val_check_interval VAL_CHECK_INTERVAL] [--trainer.log_every_n_steps LOG_EVERY_N_STEPS]
                [--trainer.accelerator.help CLASS_PATH_OR_NAME] [--trainer.accelerator ACCELERATOR] [--trainer.strategy.help CLASS_PATH_OR_NAME] [--trainer.strategy STRATEGY]
                [--trainer.sync_batchnorm {true,false}] [--trainer.precision PRECISION] [--trainer.enable_model_summary {true,false}]
                [--trainer.num_sanity_val_steps NUM_SANITY_VAL_STEPS] [--trainer.resume_from_checkpoint RESUME_FROM_CHECKPOINT] [--trainer.profiler.help CLASS_PATH_OR_NAME]
                [--trainer.profiler PROFILER] [--trainer.benchmark {true,false,null}] [--trainer.deterministic DETERMINISTIC]
                [--trainer.reload_dataloaders_every_n_epochs RELOAD_DATALOADERS_EVERY_N_EPOCHS] [--trainer.auto_lr_find AUTO_LR_FIND]
                [--trainer.replace_sampler_ddp {true,false}] [--trainer.detect_anomaly {true,false}] [--trainer.auto_scale_batch_size AUTO_SCALE_BATCH_SIZE]
                [--trainer.plugins.help CLASS_PATH_OR_NAME] [--trainer.plugins PLUGINS] [--trainer.amp_backend AMP_BACKEND] [--trainer.amp_level AMP_LEVEL]
                [--trainer.move_metrics_to_cpu {true,false}] [--trainer.multiple_trainloader_mode MULTIPLE_TRAINLOADER_MODE] [--trainer.inference_mode {true,false}]
                [--model.help CLASS_PATH_OR_NAME] --model CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE [--data.help CLASS_PATH_OR_NAME]
                [--data CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE] [--optimizer.help CLASS_PATH_OR_NAME]
                [--optimizer CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE] [--lr_scheduler.help CLASS_PATH_OR_NAME]
                [--lr_scheduler CONFIG | CLASS_PATH_OR_NAME | .INIT_ARG_NAME VALUE]
error: Parser key "data":
  Problem with given class_path 'vocos.dataset.VocosDataModule':
    No module named 'encodec'
`
I am a newer in model training. Anyone has had the same problem, please?

**Comment by giridhar-pamisetty** [comment]
Hi

Did you resolve this issue?
