### ISSUE TITLE
How to continue training using my voice from already pre-trained checkpoint?

### ISSUE THREAD

**Issue by egorsmkv** [charactr-platform/vocos#5]

**Comment by egorsmkv** [comment]
I understood:

```
python train.py -c configs/vocos.yaml --trainer.resume_from_checkpoint last.ckpt
```

**Comment by Respaired** [comment]
[rank1]: RuntimeError: Error(s) in loading state_dict for VocosExp:
[rank1]:        Unexpected key(s) in state_dict: "melspec_loss.mel_spec.spectrogram.window", "melspec_loss.mel_spec.mel_scale.fb".
